FROM debian:bookworm-slim

# Instalacja narzędzi
RUN apt-get update && apt-get install -y \
    bash \
    postgresql-client \
    gdal-bin \
    wget \
    unzip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY scripts/setup_prg.sh .
RUN chmod +x setup_prg.sh

CMD ["/bin/bash", "./setup_prg.sh"]